name: LTS EMPUS Kernel CI

on:
  push:
    tags:
      - 'linux-wsl-lts-6.12.[0-9]+-empus-[0-9]+'

run-name: LTS EMPUS Build ${{ github.ref_name }}

jobs:
  call-core-workflow:
    name: LTS EMPUS Kernel Build
    uses: Nevuly/WSL2-Linux-Kernel-Rolling-LTS/.github/workflows/build.yml@master
    with:
      tag_name: ${{ github.ref_name }}
      build_type: empus
      build_rt: true
      build_zfs: true
      is_release: false
    secrets: inherit
