name: LTS Kernel CI

on:
  push:
    tags:
      - 'linux-wsl-lts-6.18.[0-9]+'
    pull_request:
      branches:
        - 'wsl-6.18-lts'

run-name: LTS Release Build ${{ github.ref_name }}

jobs:
  call-core-workflow:
    name: LTS Kernel Build
    uses: Nevuly/WSL2-Linux-Kernel-Rolling-LTS/.github/workflows/build.yml@master
    with:
      tag_name: ${{ github.ref_name }}
      build_type: current
      build_rt: true
      build_zfs: true
      is_release: ${{ github.event_name != 'pull_request' }}
    secrets: inherit
